version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
  task-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: task-manager
    ports:
      - "8080:8080"
    environment:
      - SPRING_APPLICATION_NAME=task-manager
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb/taskmanager
    depends_on:
      - mongodb